//--------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//--------------------------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using MediatR;
using Project.Shared;
using SourceGenerator.MediatR.Proxy.Tests.TestInputs;

namespace Project.Application.Services
{
    public class MyService : IMyService
    {
        private readonly IMediator mediator;
        public MyService(IMediator mediator)
        {
            this.mediator = mediator;
        }

        public System.Threading.Tasks.Task<SourceGenerator.MediatR.Proxy.Tests.TestInputs.MyQueryResultType> My(SourceGenerator.MediatR.Proxy.Tests.TestInputs.MyQuery query, CancellationToken cancellationToken = default) => mediator.Send(query, cancellationToken);
    }
}