name: Release

on:
  push:
    tags:
    - '*.*.*'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1

jobs:
  build:
    # strategy:
    #   fail-fast: false
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
            
    - name: Build and Test
      run: ./build.ps1
      shell: pwsh
    
    - name: Push to Nuget Pkg GitHub
      env:
          NUGET_URL: https://api.nuget.org/v3/index.json
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: ./push.ps1
      shell: pwsh
    
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: artifacts/**/*
