name: Release

on:
  push:
    tags:
    - '*.*.*'

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo in the console output
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience to skip caching NuGet packages and speed up the build
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry to Microsoft

jobs:
  build:
    # strategy:
    #   fail-fast: false
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
            
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Pack Generator
      run: dotnet pack src/SourceGenerator.MediatR.Proxy/SourceGenerator.MediatR.Proxy.csproj -c Release --no-restore --no-build --include-symbols -p:SymbolPackageFormat=snupkg -o artifacts

    - name: Pack Contract
      run: dotnet pack src/SourceGenerator.MediatR.Proxy.Contracts/SourceGenerator.MediatR.Proxy.Contracts.csproj -c Release --no-restore --no-build --include-symbols -p:SymbolPackageFormat=snupkg -o artifacts

    - name: Upload Nuget Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-nuget
        path: artifacts

  publish-nuget:
    runs-on: ubuntu-latest
    name: Publish NuGet Packages
    needs: [build]
    
    steps:
      - name: Download NuGet Artifact
        uses: actions/download-artifact@v3
        with:
           name: release-nuget
           path: artifacts    

      - name: Push to NuGet
        run: dotnet nuget push artifacts/*.nupkg --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}

